language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
matrix:
  exclude:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_failure:
  - echo --------------- Begin > lumen.log ---------------
  - cat storage/logs/lumen.log
  - echo --------------- End   > lumen.log ---------------